### Register an user
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Arteaga",
    "email": "omen@gmail.com",
    "phone": "8975-8799",
    "password": "omentruco"
}
### Register an user
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Arteaga",
    "email": "omen2@gmail.com",
    "phone": "8975-8799",
    "password": "omentruco"
}

### Register an admin
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Luis",
    "lastName": "Martinez",
    "email": "lkez@gmail.com",
    "phone": "9435-8799",
    "role": "Administrador",
    "password": "lkezhn"
}

### Login user
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "omen2@gmail.com",
    "password": "omentruco"
}

### Login admin
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "lkez@gmail.com",
    "password": "lkezhn"
}

### Get my user's info
GET  http://localhost:4000/users/my_details HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpYXQiOjE2MjkyMTQ5NTAsImV4cCI6MTY2NTIxMTM1MH0.ZRBhoK677sSwN1lUbgSW5lL2kbgUscoifXNUytcnCqc


### Get user's info
GET http://localhost:4000/users/user/3 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpYXQiOjE2MjkyMTQ5NTAsImV4cCI6MTY2NTIxMTM1MH0.ZRBhoK677sSwN1lUbgSW5lL2kbgUscoifXNUytcnCqc


### Get all user's info
GET http://localhost:4000/users/page=1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Update user's info
PUT http://localhost:4000/users/2 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

{
    "firstName": "Ana",
    "lastName": "Hernandez",
    "email": "anacleto@gmail.com",
    "phone": "8947-8799" 
}

### Delete user's info
DELETE http://localhost:4000/users/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Get municipalities according to its id (id: 8 -> Fracisco Morazán)
GET http://localhost:4000/filters/municipality HTTP/1.1
Content-Type: application/json

{
    "id": "8"
}

### Get all departments
GET http://localhost:4000/filters/department HTTP/1.1
Content-Type: application/json

### Get all categories
GET http://localhost:4000/category/ HTTP/1.1
Content-Type: application/json

### Get the most popular categories
POST http://localhost:4000/category/popular HTTP/1.1
Content-Type: application/json

### Verifies if the user is logged in when trying to access the wishlist page
GET http://localhost:4000/home/wishlist HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

###
POST http://localhost:4000/qualification/add HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6IlVzdWFyaW8iLCJpYXQiOjE2MjkyMzY4NjQsImV4cCI6MTY2NTIzMzI2NH0.KrhjGs9OQb3o2oWvwDCdIPeZyntk7RgvV4vMa1b7nko

{
    "qualifiedUser": "2",
    "qualification": "4.0",
    "comment": "A good product for me"
}

###
GET http://localhost:4000/qualification/2 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpYXQiOjE2MjkyMzY0MDUsImV4cCI6MTY2NTIzMjgwNX0.2m8oKPFl_3IHUcLGHaZ5-OXGl52xlfoldUjgrUuzaFQ
