POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Arteaga",
    "email": "omen@gmail.com",
    "phone": "8975-8799",
    "password": "omentruco"
}

### Login
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "omen@gmail.com",
    "password": "omentruco"
}

###
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Andrea",
    "lastName": "Hernandez",
    "email": "andrea_her@gmail.com",
    "phone": "3245-8578",
    "password": "admin"
}

### Login
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "andrea_her@gmail.com",
    "password": "admin"
}

### Register an admin
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Luis",
    "lastName": "Martinez",
    "email": "lkez@gmail.com",
    "phone": "9435-8799",
    "password": "lkezhn"
}

### Login
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "lkez@gmail.com",
    "password": "lkezhn"
}

#------------------------ PÁGINA DE USUARIO ------------------------

### Información del Usuario
GET http://localhost:4000/users/my_details HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Obtiene la lista de los productos que ha publicado un usuario
POST http://localhost:4000/users/published HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

#------------------------ PÁGINA DE PRODUCTO ------------------------

### Retorna la información de **todos** los productos de una categoria en especifico (se tiene que hacer un request del id de la categoria 1-13)
GET http://localhost:4000/products/productCategory/1 HTTP/1.1
Content-Type: application/json

### Retorna la información de un solo producto
GET http://localhost:4000/products/2 HTTP/1.1
Content-Type: application/json

### Obtiene los comentarios de los productos (se tiene que hacer un request del id del producto)
GET http://localhost:4000/comments/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token 

### Publicar comentario en producto
POST http://localhost:4000/comments/publish/1/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

{
    "comment": "test"
}

#------------------------ SUSCRIPCIONES ------------------------

### Suscribirse a categoria (1 - 13)
POST http://localhost:4000/category/1/suscribe HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### se Desuscribirse a categoria (1 - 13)
GET http://localhost:4000/category/2/unsuscribe HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Obtener categorias a las que esta suscrito un usuario
GET http://localhost:4000/category/suscribed HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

#------------------------ LISTADO DE PRODUCTOS Y CATEGORIAS ------------------------

### Retorna  la información de **todos** los productos publicados (Sin registrar)
POST http://localhost:4000/products/productInfo HTTP/1.1
Content-Type: application/json

### Get all categories
GET http://localhost:4000/category/ HTTP/1.1
Content-Type: application/json

#------------------------ LISTA DE DESEO ------------------------

### Obtiene la lista de deseo
GET http://localhost:4000/home/wishlist HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IlVzdWFyaW8iLCJpYXQiOjE2Mjc1MDMzMjQsImV4cCI6MTY2MzQ5OTcyNH0.A5QVQAI_GzGRFZNhpZ0OoE4nPOIkkdzW8uGhLP4CmEo

### Se añade el producto a la lista de deseo (se tiene que hacer un request del id del producto)
GET http://localhost:4000/home/subscribe/1 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IlVzdWFyaW8iLCJpYXQiOjE2Mjc1MDMzMjQsImV4cCI6MTY2MzQ5OTcyNH0.A5QVQAI_GzGRFZNhpZ0OoE4nPOIkkdzW8uGhLP4CmEo

### Se añade el producto a la lista de deseo (se tiene que hacer un request del id del producto) (Hacerlo por postman) 
GET http://localhost:4000/products/ HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

{
    "productID": "1"
}

### Elimina del Wishlist
GET http://localhost:4000/home/removeSub/1 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IlVzdWFyaW8iLCJpYXQiOjE2Mjc1MDMzMjQsImV4cCI6MTY2MzQ5OTcyNH0.A5QVQAI_GzGRFZNhpZ0OoE4nPOIkkdzW8uGhLP4CmEo


###
POST http://localhost:4000/filters/ HTTP/1.1
Content-Type: application/json

{
    "Department": "1",
    "Municipality": "1",
    "minPrice":"100",
    "maxPrice":"50000",
    "order": "ASC"
}