### Register User
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Arteaga",
    "email": "xdarktheboss@gmail.com",
    "phone": "8975-8799",
    "password": "omentruco"
}

### Login User
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "xdarktheboss@gmail.com",
    "password": "omentruco"
}

### Register User
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Andrea",
    "lastName": "Hernandez",
    "email": "hernandez.anaevelin@gmail.com",
    "phone": "3245-8578",
    "password": "admin"
}

### Login User
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "hernandez.anaevelin@gmail.com",
    "password": "admin"
}

### Register User
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Luis",
    "lastName": "Martinez",
    "email": "lkez@gmail.com",
    "phone": "9435-8799",
    "password": "lkezhn"
}

### Login User
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "lkez@gmail.com",
    "password": "lkezhn"
}

### Register User
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Josue",
    "lastName": "Izaguirre",
    "email": "josue.izaguirre@siacerp.com",
    "phone": "9435-8799",
    "password": "josuecrack"
}

### Login User
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "josue.izaguirre@siacerp.com",
    "password": "josuecrack"
}

### Register User
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Juan",
    "lastName": "Boquin",
    "email": "juan.boquin@unah.hn",
    "phone": "9435-8799",
    "password": "juancito"
}

### Login User
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "juan.boquin@unah.hn",
    "password": "juancito"
}

### Register Administrator
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ana",
    "lastName": "Hernandez",
    "email": "aeherm0999@outlook.com",
    "phone": "9435-8799",
    "role": "Administrador",
    "password": "admin"
}

### Login Administrator
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "aeherm0999@outlook.com",
    "password": "admin"
}

#------------------------ PÁGINA DE USUARIO ------------------------

### Información del Usuario
GET http://localhost:4000/users/my_details HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Obtiene la lista de los productos que ha publicado un usuario
POST http://localhost:4000/users/published HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Obtiene la lista de los productos que ha publicado un usuario en especifico
POST http://localhost:4000/users/publishedSpecific/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

#------------------------ PÁGINA DE PRODUCTO ------------------------

### Retorna la información de **todos** los productos de una categoria en especifico (se tiene que hacer un request del id de la categoria 1-13)
GET http://localhost:4000/products/productCategory/1 HTTP/1.1
Content-Type: application/json

### Retorna la información de un solo producto
GET http://localhost:4000/products/1 HTTP/1.1
Content-Type: application/json

### Obtiene los comentarios de los productos (se tiene que hacer un request del id del producto)
GET http://localhost:4000/comments/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token 

### Publicar comentario en producto
POST http://localhost:4000/comments/publish/1/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

{
    "comment": "test"
}

#------------------------ SUSCRIPCIONES ------------------------

### Suscribirse a categoria (1 - 13)
POST http://localhost:4000/category/1/suscribe HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### se Desuscribirse a categoria (1 - 13)
GET http://localhost:4000/category/2/unsuscribe HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Obtener categorias a las que esta suscrito un usuario
GET http://localhost:4000/category/suscribed HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

#------------------------ LISTADO DE PRODUCTOS Y CATEGORIAS ------------------------
### Obtener  todos los productos (admin)=
GET http://localhost:4000/products/page=1 HTTP/1.1
Content-Type: application/json

### Retorna  la información de **todos** los productos publicados (Sin registrar)
POST http://localhost:4000/products/productInfo/page=1 HTTP/1.1
Content-Type: application/json

### Get all products
POST http://localhost:4000/products/getAllProducts HTTP/1.1
Content-Type: application/json

### Get all products for config
POST http://localhost:4000/products/getAllProductsConfig HTTP/1.1
Content-Type: application/json

### Get all products Limit
POST http://localhost:4000/products/getAllProductsLimit HTTP/1.1
Content-Type: application/json

### Get all categories
GET http://localhost:4000/category/ HTTP/1.1
Content-Type: application/json

### Get all categories for config
GET http://localhost:4000/category/categoryConfig HTTP/1.1
Content-Type: application/json

### Dar de baja/Vendido un producto. Parametros: 0 -> Retirado, 1 - > Vendido
PUT http://localhost:4000/products/2/0 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Dar de baja una categoria
GET http://localhost:4000/category/removeCategory/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

#------------------------ LISTA DE DESEO ------------------------

### Obtiene la lista de deseo
GET http://localhost:4000/home/wishlist HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Se añade el producto a la lista de deseo (se tiene que hacer un request del id del producto)
GET http://localhost:4000/home/subscribe/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Se añade el producto a la lista de deseo (se tiene que hacer un request del id del producto) (Hacerlo por postman) 
GET http://localhost:4000/products/ HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

{
    "productID": "1"
}

### Elimina del Wishlist
GET http://localhost:4000/home/removeSub/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Devuelve la lista de deseo de un usuario en especifico
POST http://localhost:4000/home/specificWishlist/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

#------------------------ FILTRO ------------------------

###
POST http://localhost:4000/filters/ HTTP/1.1
Content-Type: application/json

{
    "Department": "1",
    "Municipality": "1",
    "minPrice":"100",
    "maxPrice":"50000",
    "order": "ASC"
}

#------------------------ DENUNCIAS ------------------------

### Denunciar a un usuario. Parametros: Acusador/Acusado/TipoDenuncia
POST http://localhost:4000/complaints/2/1/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Listado de todas las denuncias
GET http://localhost:4000/complaints/listcomplaint HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Listado de todas las denuncias con Limite de cinco
GET http://localhost:4000/complaints/listcomplaintLimit HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Lista un denuncia especifica/
POST http://localhost:4000/complaints/getSpecificComplaint/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

### Aprobar o desestimar una denuncia. Parametros: Estado/ID Denuncia
PUT http://localhost:4000/complaints/verifyComplaint/1/1 HTTP/1.1
Content-Type: application/json
Authorization: aqui va el token

